[package]
name = "bin"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
library = {path="../library"}
tokio = { version = "*", features = ["rt","macros"] }
dotenv={version="*"}
uuid = { version = "1.3.3", features = ["v4", "fast-rng", "macro-diagnostics","serde" ]}
chrono = "*"
async-trait = {version="*"}
serde = {version="*",features=["derive"]}
serde_json = "*"
axum = {version="*"}
axum-macros = {version="*"}
utoipa = {version="*",features=["axum_extras","uuid"]}
utoipa-swagger-ui = { version="*" , features=["axum"] }
tower = { version = "0.4", features = ["util", "timeout"] }
tower-http = { version = "0.4.0", features = ["add-extension", "trace","cors"] }
tracing = "*"
tracing-subscriber = { version = "*", features = ["env-filter"] }
